# Generated by Django 3.2 on 2024-02-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230617_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='what_you_learn',
            name='course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='deadline',
            new_name='disk_space',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='author',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='featured_video',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='What_you_learn',
        ),
    ]
