# Generated by Django 3.2 on 2024-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240219_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='monthly',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='featuredimg'),
        ),
    ]
